### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by zuuritaly** [bird-house/eggshell#18]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Zuur

Graphic Designer

**Comment by nilshempelmann** [comment]
we already have a logo. 
https://github.com/bird-house/birdhouse-docs/tree/master/logos 

Thanks

**Comment by zuuritaly** [comment]
Ok, sorry! 
If you have other project that you need a logo, I will be happy to design something.

Best Regards
