### ISSUE TITLE
remove flyingpigeon dependencies

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/eggshell#19]
eggshell is based on function originally developed in flyingpigeon. 
There are still many flyingpigeon dependencies which needs to be removed

**Comment by cehbrecht** [comment]
With PR #26 the dependency list is mainly Python only :) When integrating legacy code we need to add optional dependencies. I started somethin (taken from pywps) in the `eggshell.dependencies` module:

https://github.com/bird-house/eggshell/blob/master/eggshell/dependencies.py
