### ISSUE TITLE
include "make install"

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/eggshell#2]
included the make install mechanism from hummingbird. 
Needs to be streamlined since eggshell is not a WPS. 
make start,status,stop is not necessary

**Comment by cehbrecht** [comment]
`eggshell` is a python library. We won't use the Makefile/buildout mechanisms from the WPS birds. 

Examples: 
* birdy: https://github.com/bird-house/birdy 
* owslib: https://github.com/geopython/OWSLib
