### ISSUE TITLE
Where is a good place for shapefiles etc ?

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/eggshell#20]
Currently there are shapefile prepared for polygon subsetting in flyingpigeon. 
Now with the existing of eggshell, should the shapefiles being moved as well?

**Comment by huard** [comment]
I think the shapefiles should be in the same package they are used, unless they are used in multiple packages.

**Comment by nilshempelmann** [comment]
The shapefiles are used for polygon subsetting and appropriate functions are migrated to eggshell. following your logic, the shp should migrate there as well. 
https://github.com/bird-house/eggshell/issues/22

**Comment by huard** [comment]
I guess I meant they should be with the bird that offers the subsetting service. In principle, eggshell should have generic subsetting functions that work for any shapefile, correct ? Then a bird implements a subsetting process for a hard-coded set of shapefiles that installs with it. 
In short, I don't think putting shapefiles in eggshell will scale in the future if everyone puts their own shapefiles there.

**Comment by nilshempelmann** [comment]
Ok. Got it. Will adopped the fp subsetting processes.

**Comment by nilshempelmann** [comment]
Subset netcdf files - Processes are located in flyingoigeon. 
Subset module and shapefiles are located in flyingpugeon as well
