### ISSUE TITLE
Documentation :-) 

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/eggshell#3]
pointing to 
http://eggshell.readthedocs.io/en/latest/
howto:
https://tutos.readthedocs.io/en/latest/source/git_rtd.html

**Comment by nilshempelmann** [comment]
add developer guide section

**Comment by cehbrecht** [comment]
Well, you don't need to tell ... it just takes it:
https://docs.readthedocs.io/en/latest/conda.html

I just had to add `sphinx-autoapi` to the conda env. Didn't check the builds before ;)
