### ISSUE TITLE
providing eggshell as conda package

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/eggshell#4]
http://birdhouse.readthedocs.io/en/latest/dev_guide.html#building-conda-packages

**Comment by huard** [comment]
See https://github.com/bird-house/conda-recipes/pull/9
I'll probably need some help with this.

**Comment by cehbrecht** [comment]
We have a conda package:
* https://github.com/bird-house/conda-recipes/tree/master/eggshell
* https://anaconda.org/birdhouse/birdhouse-eggshell

We just need to maintain it :)
