### ISSUE TITLE
set working directory if files are produced

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/eggshell#43]
To ensure files are stored at the right place, the workdir needs to be set.

**Comment by huard** [comment]
Not sure what is needed here. In the process handler, you can always access `self.workdir`.

**Comment by nilshempelmann** [comment]
e.g. here the output_dir needs to be defined: 
https://github.com/bird-house/eggshell/blob/master/eggshell/nc/ocg_utils.py#L74
I am not sure if we can leave it like it is

**Comment by huard** [comment]
I suggest we leave it like that and pass self.workdir when calling it.

**Comment by nilshempelmann** [comment]
OK. Got it :-)
