### ISSUE TITLE
test functions failing

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/eggshell#44]
Test are currently just the rough copies of the flyingpigeon test. 
They need to be updated

**Comment by nilshempelmann** [comment]
sub-packages need the conda depenencies to pass the tests. 
@cehbrecht @huard : How to define the subpackages in the `environment.yml` / `requirements.txt`?

**Comment by cehbrecht** [comment]
@nilshempelmann You mean how to split required and optional dependencies?

The conda `environment.yml` is used for development. It may contain all (or most) dependencies needed to setup your development environment.

`requirements.txt` is used by the python package. It should only contain the required dependencies. Other dependencies may go in something like `requirements-extra.txt` or so ...

**Comment by cehbrecht** [comment]
It would be nice if can have a single conda env for development :) In the worse case we would split this one as well.

The `eggshell` conda package should only have the minimal dependencies. We can add to the docs: "if you want to use feature B, please install package abc".

**Comment by nilshempelmann** [comment]
With one single environment, I don't get the advantage of subpackages...

**Comment by cehbrecht** [comment]
... we can have a core conda enviroment to start with and adding manually packages for the wanted subpackages (described in docs). We could also prepare additional conda envs for these cases.

The testsuite maybe tagged ... ocgis tests can be skipped if ocgis is not available.

If we want to run *all* tests on travis and can't get the dependencies in a single environment then the travis script gets more complicated ... we need to prepare several envs. Not sure if travis has a special support for such cases.

**Comment by nilshempelmann** [comment]
travis is happy :-) 
all dependencies are in one environment.
