### ISSUE TITLE
make "heavy" dependencies optional

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/eggshell#5]
Currently `eggshell` has "heavy" dependencies which are required, for example:
* matplotlib
* cartopy
* ocgis

To make `eggshell` usable also for lightweight birds (wps services) we could make those dependencies optional ... functionality using these libraries is only loaded/available when the libraries are installed (ocgis, matplotlib, ...).

**Comment by huard** [comment]
I could move those utilities into subpackages. They won't be imported by `import eggshell`. 

Does that mean creating an environment-dev.yml file with those optional dependencies ?

**Comment by huard** [comment]
Also, I suppose this means that the real birds have the responsibility of having those dependencies, and not delegate non-trivial dependencies to eggshell.

**Comment by cehbrecht** [comment]
The `environment.yml` is used for development and we can keep *all* conda dependencies here, just adding a comment for optional packages. But we should split the `requirements.txt` which is used by the Python package. Maybe having something like `requirements-opt.txt`?  `-dev` is already used for the test requirements `pytest` etc. 

> Also, I suppose this means that the real birds have the responsibility of having those dependencies ..

yes.
